### ISSUE TITLE
no interpreter information for class HDTV::Fit is available

### ISSUE THREAD

**Issue by op3** [hdtv-tool/hdtv#5]
Great work moving to cmake as the build system! There still seems to be a problem in the fit library build process. I have confirmed that this error occurs on the following systems:

- Ubuntu 18.04.4, cmake 3.13.2, ROOT 6.20/00, python 2.7.17, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- Arch Linux + conda (with conda-forge), cmake 3.17.0, ROOT 6.20/04, python 3.8.2, gcc (crosstool-NG 1.23.0.450-d54ae) 7.3.0

Reproduce the problem:

1. Start hdtv. Compilation completes successfully.
2. Load a spectrum, e. g. `spectrum get tests/share/osiris_bg.spc`
3. Fit a peak, e. g. using `Q`.

Output:

```
$ ./bin/hdtv
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- ROOT Version 6.20.00 found in /soft/src/cern/root/install/6.20.00/bin/root
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmpnOQuad
[  5%] Generating G__display.cxx, libdisplay_rdict.pcm, libdisplay.rootmap
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20181206'
  Extraction of runtime standard library version was: '20191114'
Scanning dependencies of target display
[ 10%] Building CXX object CMakeFiles/display.dir/Calibration.cc.o
[ 15%] Building CXX object CMakeFiles/display.dir/DisplayFunc.cc.o
[ 26%] Building CXX object CMakeFiles/display.dir/DisplayBlock.cc.o
[ 26%] Building CXX object CMakeFiles/display.dir/DisplayCut.cc.o
[ 36%] Building CXX object CMakeFiles/display.dir/DisplayObj.cc.o
[ 36%] Building CXX object CMakeFiles/display.dir/Marker.cc.o
[ 47%] Building CXX object CMakeFiles/display.dir/DisplayStack.cc.o
[ 47%] Building CXX object CMakeFiles/display.dir/MTViewer.cc.o
[ 52%] Building CXX object CMakeFiles/display.dir/Painter.cc.o
[ 57%] Building CXX object CMakeFiles/display.dir/DisplaySpec.cc.o
[ 63%] Building CXX object CMakeFiles/display.dir/XMarker.cc.o
[ 73%] Building CXX object CMakeFiles/display.dir/View.cc.o
[ 73%] Building CXX object CMakeFiles/display.dir/Viewer.cc.o
[ 78%] Building CXX object CMakeFiles/display.dir/View1D.cc.o
[ 89%] Building CXX object CMakeFiles/display.dir/View2D.cc.o
[ 89%] Building CXX object CMakeFiles/display.dir/YMarker.cc.o
[ 94%] Building CXX object CMakeFiles/display.dir/G__display.cxx.o
[100%] Linking CXX shared library libdisplay.so
[100%] Built target display
[100%] Built target display
Install the project...
-- Install configuration: "Release"
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libdisplay.so
-- Set runtime path of "/home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libdisplay.so" to ""
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libdisplay.rootmap
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libdisplay_rdict.pcm
INFO: Rebuild library libdisplay.so in /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ROOT Version 6.20.00 found in /soft/src/cern/root/install/6.20.00/bin/root
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmpC2CVhf
[ 10%] Generating G__fit.cxx, libfit_rdict.pcm, libfit.rootmap
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20181206'
  Extraction of runtime standard library version was: '20191114'
Scanning dependencies of target fit
[ 20%] Building CXX object CMakeFiles/fit.dir/Util.cc.o
[ 30%] Building CXX object CMakeFiles/fit.dir/G__fit.cxx.o
[ 70%] Building CXX object CMakeFiles/fit.dir/Param.cc.o
[ 70%] Building CXX object CMakeFiles/fit.dir/EEFitter.cc.o
[ 70%] Building CXX object CMakeFiles/fit.dir/Fitter.cc.o
[ 70%] Building CXX object CMakeFiles/fit.dir/Integral.cc.o
[ 90%] Building CXX object CMakeFiles/fit.dir/PolyBg.cc.o
[ 90%] Building CXX object CMakeFiles/fit.dir/TheuerkaufFitter.cc.o
[100%] Linking CXX shared library libfit.so
[100%] Built target fit
[100%] Built target fit
Install the project...
-- Install configuration: "Release"
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libfit.so
-- Set runtime path of "/home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libfit.so" to ""
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libfit.rootmap
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libfit_rdict.pcm
INFO: Rebuild library libfit.so in /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ROOT Version 6.20.00 found in /soft/src/cern/root/install/6.20.00/bin/root
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmpLhoxSf
[  2%] Generating G__mfile-root.cxx, libmfile-root_rdict.pcm, libmfile-root.rootmap
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20181206'
  Extraction of runtime standard library version was: '20191114'
Scanning dependencies of target mfile-root
[  5%] Building CXX object CMakeFiles/mfile-root.dir/MatOp.cc.o
[  8%] Building CXX object CMakeFiles/mfile-root.dir/MFileHist.cc.o
[ 11%] Building C object CMakeFiles/mfile-root.dir/matop/matop_project.c.o
[ 13%] Building CXX object CMakeFiles/mfile-root.dir/MFileRoot.cc.o
[ 16%] Building CXX object CMakeFiles/mfile-root.dir/VMatrix.cc.o
[ 19%] Building C object CMakeFiles/mfile-root.dir/matop/matop_adjust.c.o
[ 22%] Building C object CMakeFiles/mfile-root.dir/matop/matop_conv.c.o
[ 25%] Building C object CMakeFiles/mfile-root.dir/mfile/src/callindir.c.o
[ 27%] Building C object CMakeFiles/mfile-root.dir/mfile/src/converters.c.o
[ 41%] Building C object CMakeFiles/mfile-root.dir/mfile/src/maccess.c.o
[ 41%] Building C object CMakeFiles/mfile-root.dir/mfile/src/gf2_minfo.c.o
[ 41%] Building C object CMakeFiles/mfile-root.dir/mfile/src/gf2_getput.c.o
[ 41%] Building C object CMakeFiles/mfile-root.dir/mfile/src/getputint.c.o
[ 41%] Building C object CMakeFiles/mfile-root.dir/mfile/src/disk_access.c.o
[ 44%] Building C object CMakeFiles/mfile-root.dir/mfile/src/lc_c1.c.o
[ 47%] Building C object CMakeFiles/mfile-root.dir/mfile/src/lc_c2.c.o
[ 50%] Building C object CMakeFiles/mfile-root.dir/mfile/src/mat_types.c.o
[ 52%] Building C object CMakeFiles/mfile-root.dir/mfile/src/lc_getput.c.o
[ 55%] Building C object CMakeFiles/mfile-root.dir/mfile/src/mate_getput.c.o
[ 58%] Building C object CMakeFiles/mfile-root.dir/mfile/src/lc_minfo.c.o
[ 61%] Building C object CMakeFiles/mfile-root.dir/mfile/src/mate_minfo.c.o
[ 63%] Building C object CMakeFiles/mfile-root.dir/mfile/src/oldmat_minfo.c.o
[ 66%] Building C object CMakeFiles/mfile-root.dir/mfile/src/shm_getput.c.o
[ 69%] Building C object CMakeFiles/mfile-root.dir/mfile/src/mopen.c.o
[ 72%] Building C object CMakeFiles/mfile-root.dir/mfile/src/minfo.c.o
[ 75%] Building C object CMakeFiles/mfile-root.dir/mfile/src/oldmat_getput.c.o
[ 80%] Building C object CMakeFiles/mfile-root.dir/mfile/src/shm_minfo.c.o
[ 80%] Building C object CMakeFiles/mfile-root.dir/mfile/src/shm_access.c.o
[ 83%] Building C object CMakeFiles/mfile-root.dir/mfile/src/specio.c.o
[ 86%] Building C object CMakeFiles/mfile-root.dir/mfile/src/trixi_getput.c.o
[ 88%] Building C object CMakeFiles/mfile-root.dir/mfile/src/txt_minfo.c.o
[ 91%] Building C object CMakeFiles/mfile-root.dir/mfile/src/trixi_minfo.c.o
[ 97%] Building C object CMakeFiles/mfile-root.dir/mfile/src/txt_getput.c.o
[ 97%] Building CXX object CMakeFiles/mfile-root.dir/G__mfile-root.cxx.o
[100%] Linking CXX shared library libmfile-root.so
[100%] Built target mfile-root
[100%] Built target mfile-root
Install the project...
-- Install configuration: "Release"
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libmfile-root.so
-- Set runtime path of "/home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libmfile-root.so" to ""
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libmfile-root.rootmap
-- Installing: /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc/lib/libmfile-root_rdict.pcm
INFO: Rebuild library libmfile-root.so in /home/user/.cache/hdtv/34017776-62000-v20.4+1.g39aaffc
HDTV - Nuclear Spectrum Analysis Tool
hdtv> spectrum get tests/share/osiris_bg.spc 
Loaded tests/share/osiris_bg.spc into 0
hdtv> 'pos' fit parameter reset to 'free'
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
In file included from libfit dictionary payload:6:
In file included from /home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:29:
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:38:3: error: unknown type name 'Param'
  Param AllocParam();
  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:39:3: error: unknown type name 'Param'
  Param AllocParam(double ival);
  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:56:19: error: use of undeclared identifier 'Background'
  std::unique_ptr<Background> fBackground;
                  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:61:32: error: unknown type name 'Param'
  void SetParameter(TF1 &func, Param &param, double ival = 0.0);
                               ^
In file included from libfit dictionary payload:6:
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:16: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
               ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:34: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
                                 ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:52: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
                                                   ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:16: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
               ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:37: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
                                    ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:55: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
                                                      ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:111:3: error: unknown type name 'Param'
  Param fPos, fAmp, fSigma1, fSigma2, fEta, fGamma;
  ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:116:27: error: unknown type name 'Param'
  void RestoreParam(const Param &param, double value, double error);
                          ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:122:25: error: expected class name
class EEFitter : public Fitter {
                        ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:131:29: error: unknown type name 'Background'
  void Fit(TH1 &hist, const Background &bg);
                            ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:139:22: error: unknown type name 'Background'
  bool Restore(const Background &bg, double ChiSquare);
                     ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:124:36: error: member initializer 'Fitter' does not name a non-static data member or base class
  EEFitter(double r1, double r2) : Fitter(r1, r2) {}
                                   ^~~~~~~~~~~~~~
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:134:30: error: use of undeclared identifier 'fNumPeaks'
  int GetNumPeaks() { return fNumPeaks; }
                             ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:136:30: error: use of undeclared identifier 'fSumFunc'
  TF1 *GetSumFunc() { return fSumFunc.get(); }
                             ^
In file included from libfit dictionary payload:8:
/home/user/hdtv/hdtv/rootext/fit/Integral.hh:197:20: error: unknown type name 'Background'
  BgIntegral(const Background *background, double r1, double r2, TAxis *axis);
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Error in <TInterpreter::AutoParse>: Error parsing payload code for class HDTV::Fit::Fitter with content:

#line 1 "libfit dictionary payload"


#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include "Background.hh"
#include "EEFitter.hh"
#include "Fitter.hh"
#include "Integral.hh"
#include "Param.hh"
#include "PolyBg.hh"
#include "TheuerkaufFitter.hh"
#include "Util.hh"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::Fitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::Fitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::Fitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
In file included from libfit dictionary payload:6:
In file included from /home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:29:
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:38:3: error: unknown type name 'Param'
  Param AllocParam();
  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:39:3: error: unknown type name 'Param'
  Param AllocParam(double ival);
  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:56:19: error: use of undeclared identifier 'Background'
  std::unique_ptr<Background> fBackground;
                  ^
/home/user/hdtv/hdtv/rootext/fit/Fitter.hh:61:32: error: unknown type name 'Param'
  void SetParameter(TF1 &func, Param &param, double ival = 0.0);
                               ^
In file included from libfit dictionary payload:6:
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:16: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
               ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:34: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
                                 ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:47:52: error: unknown type name 'Param'
  EEPeak(const Param &pos, const Param &amp, const Param &sigma1,
                                                   ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:16: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
               ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:37: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
                                    ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:48:55: error: unknown type name 'Param'
         const Param &sigma2, const Param &eta, const Param &gamma);
                                                      ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:111:3: error: unknown type name 'Param'
  Param fPos, fAmp, fSigma1, fSigma2, fEta, fGamma;
  ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:116:27: error: unknown type name 'Param'
  void RestoreParam(const Param &param, double value, double error);
                          ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:122:25: error: expected class name
class EEFitter : public Fitter {
                        ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:131:29: error: unknown type name 'Background'
  void Fit(TH1 &hist, const Background &bg);
                            ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:139:22: error: unknown type name 'Background'
  bool Restore(const Background &bg, double ChiSquare);
                     ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:124:36: error: member initializer 'Fitter' does not name a non-static data member or base class
  EEFitter(double r1, double r2) : Fitter(r1, r2) {}
                                   ^~~~~~~~~~~~~~
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:134:30: error: use of undeclared identifier 'fNumPeaks'
  int GetNumPeaks() { return fNumPeaks; }
                             ^
/home/user/hdtv/hdtv/rootext/fit/EEFitter.hh:136:30: error: use of undeclared identifier 'fSumFunc'
  TF1 *GetSumFunc() { return fSumFunc.get(); }
                             ^
In file included from libfit dictionary payload:8:
/home/user/hdtv/hdtv/rootext/fit/Integral.hh:197:20: error: unknown type name 'Background'
  BgIntegral(const Background *background, double r1, double r2, TAxis *axis);
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Error in <TInterpreter::AutoParse>: Error parsing payload code for class HDTV::Fit::TheuerkaufFitter with content:

#line 1 "libfit dictionary payload"


#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include "Background.hh"
#include "EEFitter.hh"
#include "Fitter.hh"
#include "Integral.hh"
#include "Param.hh"
#include "PolyBg.hh"
#include "TheuerkaufFitter.hh"
#include "Util.hh"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::TheuerkaufFitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::TheuerkaufFitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit::TheuerkaufFitter is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class HDTV::Fit is available even though it has a TClass initialization routine.
Traceback (most recent call last):
  File "/home/user/hdtv/hdtv/window.py", line 178, in KeyHandler
    handled = self.HandleHotkey(self.viewer.fKeySym)
  File "/home/user/hdtv/hdtv/window.py", line 81, in HandleHotkey
    node()
  File "/home/user/hdtv/hdtv/plugins/fitInterface.py", line 217, in QuickFit
    self.spectra.ExecuteFit()
  File "/home/user/hdtv/hdtv/session.py", line 168, in ExecuteFit
    fit.FitPeakFunc(spec)
  File "/home/user/hdtv/hdtv/fit.py", line 431, in FitPeakFunc
    self.fitter.FitPeaks(spec=self.spec, region=region, peaklist=peaks)
  File "/home/user/hdtv/hdtv/fitter.py", line 88, in FitPeaks
    self.peakFitter = self.peakModel.GetFitter(region, peaklist, spec.cal)
  File "/home/user/hdtv/hdtv/peakmodels/theuerkaufPeak.py", line 283, in GetFitter
    self.fFitter = ROOT.HDTV.Fit.TheuerkaufFitter(region[0], region[1])
TypeError: HDTV::Fit::TheuerkaufFitter::HDTV::Fit::TheuerkaufFitter() =>
    takes at most 0 arguments (2 given)
```

**Comment by janmayer** [comment]
I managed to reproduce the problem - it can be fixed by quitting out of hdtv after the initial build and launching it again - not quite sure why.

A Workaround would be to terminate the program after a library rebuild.
